# Generated by Django 5.0 on 2024-02-16 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Priz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('img', models.ImageField(upload_to='priz')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s.category')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='izoh')),
                ('date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Izoh', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s.student')),
            ],
        ),
    ]
