# Generated by Django 5.0 on 2024-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='Category', upload_to='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='Nomi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
