# Generated by Django 5.0 on 2024-02-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0002_category_img_alter_category_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='img',
            field=models.ImageField(blank=True, upload_to='izoh'),
        ),
    ]
